# Generated by Django 3.1.2 on 2020-10-11 19:26

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('app2021', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('link_ext', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=90)),
                ('url', models.CharField(max_length=30)),
                ('body', martor.models.MartorField()),
            ],
        ),
    ]
