# Generated by Django 3.2 on 2021-04-25 03:45

import app2021.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2021', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='preview_deskX2',
            field=models.ImageField(default=' ', upload_to='', validators=[app2021.models.prevImage_restriction]),
        ),
    ]
