# Generated by Django 3.1.2 on 2020-10-11 19:53

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('app2021', '0002_customisation_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('link_ext', models.CharField(max_length=3)),
                ('opened', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=30)),
                ('body', martor.models.MartorField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
        migrations.AddField(
            model_name='customisation',
            name='hightlight',
            field=models.ManyToManyField(to='app2021.Project'),
        ),
        migrations.AddField(
            model_name='link',
            name='Customisation',
            field=models.ManyToManyField(to='app2021.Customisation'),
        ),
        migrations.AddField(
            model_name='project',
            name='skill',
            field=models.ManyToManyField(to='app2021.Skill'),
        ),
    ]
