# Generated by Django 3.2 on 2021-04-25 04:42

import app2021.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2021', '0003_alter_case_preview_deskx2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='preview_deskX2',
            field=models.ImageField(default=' ', upload_to='preview/', validators=[app2021.models.prevImage_restriction]),
        ),
        migrations.AlterField(
            model_name='caseimage',
            name='imageX2',
            field=models.ImageField(default='', upload_to='cases/', validators=[app2021.models.caseImage_restriction]),
        ),
    ]
