# Generated by Django 3.1.2 on 2020-10-11 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app2021', '0003_auto_20201011_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='customisation',
            name='hightlight_header',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customisation',
            name='intro',
            field=models.CharField(default=django.utils.timezone.now, max_length=220),
            preserve_default=False,
        ),
    ]
