# Generated by Django 3.2 on 2021-04-25 11:34

import app2021.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2021', '0004_auto_20210425_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='preview_deskX2',
            field=models.ImageField(default='', upload_to='preview/', validators=[app2021.models.prevImage_restriction]),
        ),
    ]
