# Generated by Django 3.1.2 on 2020-10-13 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2021', '0004_auto_20201011_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='Customisation',
        ),
        migrations.AddField(
            model_name='link',
            name='Customisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app2021.customisation'),
        ),
    ]
