# Generated by Django 3.1.2 on 2020-10-13 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2021', '0005_auto_20201013_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='Customisation',
            new_name='customisation',
        ),
    ]
