# Generated by Django 3.1.2 on 2020-10-13 20:10

import app2021.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2021', '0006_auto_20201013_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customisation',
            name='link_ext',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='link',
            name='link_ext',
            field=models.CharField(default=app2021.models.random_string, max_length=3),
        ),
    ]
