name: DO Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Django app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            mkdir temp_be
            cd temp_be
            git clone git@github.com:ViktorDyukov/portfolio-backend.git
            rm -r /home/django/portfolio-backend/*.*
            cp -r portfolio-backend/. /home/django/portfolio-backend/
            cp /home/django/settings.py /home/django/portfolio-backend/vi2021/
            cd ..
            rm -r temp_be
